In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option("display.max_rows",None)

In [3]:
df = pd.read_csv("job_dataset.csv")
df

,job_id,job_title,company,location,skills_required,experience_years,salary
0,1,Data Analyst,TCS,Hyderabad,Python SQL Excel,1,400000
1,2,Data Scientist,Infosys,Bangalore,Python Machine Learning SQL,3,900000
2,3,Software Engineer,Wipro,Chennai,Java C++ SQL,2,600000
3,4,Machine Learning Engineer,Amazon,Hyderabad,Python Deep Learning ML,4,1200000
4,5,Backend Developer,Google,Bangalore,Python Java SQL,3,1100000
5,6,Frontend Developer,Microsoft,Pune,JavaScript HTML CSS,2,700000
6,7,AI Engineer,Accenture,Hyderabad,Python NLP Deep Learning,5,1500000
7,8,Business Analyst,Capgemini,Mumbai,Excel SQL Power BI,2,650000
8,9,Python Developer,TCS,Chennai,Python Django SQL,1,500000
9,10,SQL Developer,Infosys,Pune,SQL Database ETL,2,550000
10,11,Data Analyst,Wipro,Delhi,Excel SQL Tableau,1,450000
11,12,Data Scientist,Amazon,Bangalore,Python ML DL SQL,4,1300000
12,13,Software Engineer,Google,Hyderabad,Java Spring Boot SQL,3,1000000
13,14,Machine Learning Engineer,Microsoft,Chennai,Python ML AI,3,1150000
14,15,Backend Developer,Accenture,Pune,Java Python SQL,2,800000
15,16,Frontend Developer,Capgemini,Hyderabad,JavaScript React CSS,2,750000
16,17,AI Engineer,TCS,Bangalore,Python Deep Learning NLP,4,1400000
17,18,Business Analyst,Infosys,Mumbai,Excel Power BI SQL,3,700000
18,19,Python Developer,Wipro,Chennai,Python Flask SQL,1,520000
19,20,SQL Developer,Amazon,Hyderabad,SQL ETL Data Warehousing,3,900000
20,21,Data Analyst,Google,Bangalore,Excel SQL Python,2,650000
21,22,Data Scientist,Microsoft,Pune,Python ML AI SQL,5,1500000
22,23,Software Engineer,Accenture,Chennai,Java C++ OOP,2,600000
23,24,Machine Learning Engineer,Capgemini,Hyderabad,Python ML DL NLP,4,1200000
24,25,Backend Developer,TCS,Bangalore,Python Django SQL,2,700000
25,26,Frontend Developer,Infosys,Chennai,HTML CSS JavaScript,1,450000
26,27,AI Engineer,Wipro,Pune,Python Deep Learning AI,5,1600000
27,28,Business Analyst,Amazon,Mumbai,Excel Tableau SQL,3,800000
28,29,Python Developer,Google,Hyderabad,Python Flask API,2,750000
29,30,SQL Developer,Microsoft,Bangalore,SQL ETL Power BI,3,950000
30,31,Data Analyst,TCS,Pune,Excel SQL Python,2,600000
31,32,Data Scientist,Infosys,Hyderabad,Python ML DL,4,1250000
32,33,Software Engineer,Wipro,Bangalore,Java Spring SQL,3,850000
33,34,Machine Learning Engineer,Amazon,Chennai,Python ML NLP,4,1200000
34,35,Backend Developer,Google,Hyderabad,Python Django API,3,950000
35,36,Frontend Developer,Microsoft,Bangalore,React JS CSS,2,800000
36,37,AI Engineer,Accenture,Pune,Python AI DL NLP,5,1550000
37,38,Business Analyst,Capgemini,Chennai,Excel SQL BI,2,700000
38,39,Python Developer,TCS,Hyderabad,Python Flask SQL,1,480000
39,40,SQL Developer,Infosys,Bangalore,SQL ETL DW,3,920000
40,41,Data Analyst,Wipro,Pune,Excel Tableau SQL,2,610000
41,42,Data Scientist,Amazon,Hyderabad,Python ML AI,4,1350000
42,43,Software Engineer,Google,Chennai,Java OOP SQL,2,750000
43,44,Machine Learning Engineer,Microsoft,Bangalore,Python ML DL,3,1150000
44,45,Backend Developer,Accenture,Hyderabad,Java Python API,2,820000
45,46,Frontend Developer,Capgemini,Pune,HTML CSS JS,1,500000
46,47,AI Engineer,TCS,Chennai,Python DL NLP,5,1500000
47,48,Business Analyst,Infosys,Hyderabad,Excel BI SQL,3,720000
48,49,Python Developer,Wipro,Bangalore,Python Django API,2,700000
49,50,SQL Developer,Amazon,Chennai,SQL ETL BI,3,910000
50,51,Data Analyst,Google,Pune,Excel SQL Python,2,640000
51,52,Data Scientist,Microsoft,Hyderabad,Python ML AI,4,1400000
52,53,Software Engineer,Accenture,Bangalore,Java Spring Boot,3,900000
53,54,Machine Learning Engineer,Capgemini,Chennai,Python ML NLP DL,4,1250000
54,55,Backend Developer,TCS,Hyderabad,Python Django SQL,2,720000
55,56,Frontend Developer,Infosys,Bangalore,React JS CSS HTML,2,780000
56,57,AI Engineer,Wipro,Pune,Python AI NLP DL,5,1600000
57,58,Business Analyst,Amazon,Chennai,Excel SQL BI,3,820000
58,59,Python Developer,Google,Hyderabad,Python Flask API,2,760000
59,60,SQL Developer,Microsoft,Bangalore,SQL ETL Power BI,3,960000
60,61,Data Analyst,TCS,Chennai,Excel SQL Python,1,500000
61,62,Data Scientist,Infosys,Pune,Python ML DL AI,4,1300000
62,63,Software Engineer,Wipro,Hyderabad,Java OOP SQL,2,700000
63,64,Machine Learning Engineer,Amazon,Bangalore,Python ML NLP,4,1350000
64,65,Backend Developer,Google,Chennai,Python API SQL,3,900000
65,66,Frontend Developer,Microsoft,Hyderabad,HTML CSS JS React,2,820000
66,67,AI Engineer,Accenture,Bangalore,Python DL NLP AI,5,1550000
67,68,Business Analyst,Capgemini,Pune,Excel BI SQL,2,710000
68,69,Python Developer,TCS,Hyderabad,Python Django SQL,1,520000
69,70,SQL Developer,Infosys,Chennai,SQL ETL DW,3,930000
70,71,Data Analyst,Google,Bangalore,Python SQL Excel,2,650000
71,72,Data Scientist,Microsoft,Hyderabad,Python ML AI SQL,4,1400000
72,73,Software Engineer,Accenture,Pune,Java Spring Boot SQL,3,900000
73,74,Machine Learning Engineer,Capgemini,Chennai,Python ML NLP DL,4,1250000
74,75,Backend Developer,TCS,Hyderabad,Python Django API,2,720000
75,76,Frontend Developer,Infosys,Bangalore,React JS CSS HTML,2,780000
76,77,AI Engineer,Wipro,Pune,Python AI NLP DL,5,1600000
77,78,Business Analyst,Amazon,Chennai,Excel SQL BI,3,820000
78,79,Python Developer,Google,Hyderabad,Python Flask API,2,760000
79,80,SQL Developer,Microsoft,Bangalore,SQL ETL Power BI,3,960000
80,81,Data Analyst,TCS,Chennai,Excel SQL Python,1,500000
81,82,Data Scientist,Infosys,Pune,Python ML DL AI,4,1300000
82,83,Software Engineer,Wipro,Hyderabad,Java OOP SQL,2,700000
83,84,Machine Learning Engineer,Amazon,Bangalore,Python ML NLP,4,1350000
84,85,Backend Developer,Google,Chennai,Python API SQL,3,900000
85,86,Frontend Developer,Microsoft,Hyderabad,HTML CSS JS React,2,820000
86,87,AI Engineer,Accenture,Bangalore,Python DL NLP AI,5,1550000
87,88,Business Analyst,Capgemini,Pune,Excel BI SQL,2,710000
88,89,Python Developer,TCS,Hyderabad,Python Django SQL,1,520000
89,90,SQL Developer,Infosys,Chennai,SQL ETL DW,3,930000
90,91,Data Analyst,Wipro,Bangalore,Excel SQL Tableau,2,620000
91,92,Data Scientist,Amazon,Hyderabad,Python ML AI,4,1350000
92,93,Software Engineer,Google,Pune,Java Spring Boot,3,950000
93,94,Machine Learning Engineer,Microsoft,Chennai,Python ML DL,3,1200000
94,95,Backend Developer,Accenture,Bangalore,Java Python API,2,850000
95,96,Frontend Developer,Capgemini,Hyderabad,HTML CSS JS,1,520000
96,97,AI Engineer,TCS,Pune,Python DL NLP,5,1500000
97,98,Business Analyst,Infosys,Chennai,Excel BI SQL,3,720000
98,99,Python Developer,Wipro,Hyderabad,Python Django API,2,710000
99,100,SQL Developer,Amazon,Bangalore,SQL ETL BI,3,940000
100,101,Data Analyst,Google,Chennai,Excel SQL Python,2,630000
101,102,Data Scientist,Microsoft,Bangalore,Python ML AI,4,1400000
102,103,Software Engineer,Accenture,Hyderabad,Java OOP SQL,2,720000
103,104,Machine Learning Engineer,Capgemini,Pune,Python ML NLP DL,4,1250000
104,105,Backend Developer,TCS,Chennai,Python Django SQL,2,700000
105,106,Frontend Developer,Infosys,Hyderabad,React JS CSS HTML,2,780000
106,107,AI Engineer,Wipro,Bangalore,Python AI NLP DL,5,1600000
107,108,Business Analyst,Amazon,Pune,Excel SQL BI,3,800000
108,109,Python Developer,Google,Chennai,Python Flask API,2,760000
109,110,SQL Developer,Microsoft,Hyderabad,SQL ETL Power BI,3,960000
110,111,Data Analyst,TCS,Bangalore,Excel SQL Python,1,520000
111,112,Data Scientist,Infosys,Chennai,Python ML DL AI,4,1300000
112,113,Software Engineer,Wipro,Pune,Java OOP SQL,2,710000
113,114,Machine Learning Engineer,Amazon,Hyderabad,Python ML NLP,4,1350000
114,115,Backend Developer,Google,Bangalore,Python API SQL,3,920000
115,116,Frontend Developer,Microsoft,Chennai,HTML CSS JS React,2,800000
116,117,AI Engineer,Accenture,Hyderabad,Python DL NLP AI,5,1550000
117,118,Business Analyst,Capgemini,Bangalore,Excel BI SQL,2,720000
118,119,Python Developer,TCS,Pune,Python Django SQL,1,500000
119,120,SQL Developer,Infosys,Hyderabad,SQL ETL DW,3,930000
120,121,Data Analyst,Wipro,Chennai,Excel SQL Tableau,2,620000
121,122,Data Scientist,Amazon,Bangalore,Python ML AI,4,1350000
122,123,Software Engineer,Google,Hyderabad,Java Spring Boot,3,950000
123,124,Machine Learning Engineer,Microsoft,Pune,Python ML DL,3,1200000
124,125,Backend Developer,Accenture,Chennai,Java Python API,2,850000
125,126,Frontend Developer,Capgemini,Bangalore,HTML CSS JS,1,520000
126,127,AI Engineer,TCS,Hyderabad,Python DL NLP,5,1500000
127,128,Business Analyst,Infosys,Pune,Excel BI SQL,3,720000
128,129,Python Developer,Wipro,Chennai,Python Django API,2,710000
129,130,SQL Developer,Amazon,Hyderabad,SQL ETL BI,3,940000
130,131,Data Analyst,Google,Bangalore,Excel SQL Python,2,640000
131,132,Data Scientist,Microsoft,Chennai,Python ML AI,4,1400000
132,133,Software Engineer,Accenture,Hyderabad,Java OOP SQL,2,720000
133,134,Machine Learning Engineer,Capgemini,Bangalore,Python ML NLP DL,4,1250000
134,135,Backend Developer,TCS,Pune,Python Django SQL,2,700000
135,136,Frontend Developer,Infosys,Hyderabad,React JS CSS HTML,2,780000
136,137,AI Engineer,Wipro,Chennai,Python AI NLP DL,5,1600000
137,138,Business Analyst,Amazon,Bangalore,Excel SQL BI,3,800000
138,139,Python Developer,Google,Pune,Python Flask API,2,760000
139,140,SQL Developer,Microsoft,Hyderabad,SQL ETL Power BI,3,960000
140,141,Data Analyst,TCS,Chennai,Excel SQL Python,1,520000
141,142,Data Scientist,Infosys,Bangalore,Python ML DL AI,4,1300000
142,143,Software Engineer,Wipro,Hyderabad,Java OOP SQL,2,710000
143,144,Machine Learning Engineer,Amazon,Pune,Python ML NLP,4,1350000
144,145,Backend Developer,Google,Chennai,Python API SQL,3,920000
145,146,Frontend Developer,Microsoft,Bangalore,HTML CSS JS React,2,800000
146,147,AI Engineer,Accenture,Hyderabad,Python DL NLP AI,5,1550000
147,148,Business Analyst,Capgemini,Chennai,Excel BI SQL,2,720000
148,149,Python Developer,TCS,Bangalore,Python Django SQL,1,500000
149,150,SQL Developer,Infosys,Pune,SQL ETL DW,3,930000
150,151,Data Analyst,Wipro,Hyderabad,Excel SQL Tableau,2,620000
151,152,Data Scientist,Amazon,Chennai,Python ML AI,4,1350000
152,153,Software Engineer,Google,Bangalore,Java Spring Boot,3,950000
153,154,Machine Learning Engineer,Microsoft,Hyderabad,Python ML DL,3,1200000
154,155,Backend Developer,Accenture,Pune,Java Python API,2,850000
155,156,Frontend Developer,Capgemini,Chennai,HTML CSS JS,1,520000
156,157,AI Engineer,TCS,Bangalore,Python DL NLP,5,1500000
157,158,Business Analyst,Infosys,Hyderabad,Excel BI SQL,3,720000
158,159,Python Developer,Wipro,Pune,Python Django API,2,710000
159,160,SQL Developer,Amazon,Chennai,SQL ETL BI,3,940000
160,161,Data Analyst,Google,Hyderabad,Excel SQL Python,2,640000
161,162,Data Scientist,Microsoft,Pune,Python ML AI,4,1400000
162,163,Software Engineer,Accenture,Chennai,Java OOP SQL,2,720000
163,164,Machine Learning Engineer,Capgemini,Hyderabad,Python ML NLP DL,4,1250000
164,165,Backend Developer,TCS,Bangalore,Python Django SQL,2,700000
165,166,Frontend Developer,Infosys,Chennai,React JS CSS HTML,2,780000
166,167,AI Engineer,Wipro,Hyderabad,Python AI NLP DL,5,1600000
167,168,Business Analyst,Amazon,Bangalore,Excel SQL BI,3,800000
168,169,Python Developer,Google,Chennai,Python Flask API,2,760000
169,170,SQL Developer,Microsoft,Pune,SQL ETL Power BI,3,960000
170,171,Data Analyst,TCS,Hyderabad,Excel SQL Python,1,520000
171,172,Data Scientist,Infosys,Bangalore,Python ML DL AI,4,1300000
172,173,Software Engineer,Wipro,Chennai,Java OOP SQL,2,710000
173,174,Machine Learning Engineer,Amazon,Hyderabad,Python ML NLP,4,1350000
174,175,Backend Developer,Google,Bangalore,Python API SQL,3,920000
175,176,Frontend Developer,Microsoft,Chennai,HTML CSS JS React,2,800000
176,177,AI Engineer,Accenture,Hyderabad,Python DL NLP AI,5,1550000
177,178,Business Analyst,Capgemini,Bangalore,Excel BI SQL,2,720000
178,179,Python Developer,TCS,Pune,Python Django SQL,1,500000
179,180,SQL Developer,Infosys,Hyderabad,SQL ETL DW,3,930000
180,181,Data Analyst,Wipro,Chennai,Excel SQL Tableau,2,620000
181,182,Data Scientist,Amazon,Bangalore,Python ML AI,4,1350000
182,183,Software Engineer,Google,Hyderabad,Java Spring Boot,3,950000
183,184,Machine Learning Engineer,Microsoft,Pune,Python ML DL,3,1200000
184,185,Backend Developer,Accenture,Chennai,Java Python API,2,850000
185,186,Frontend Developer,Capgemini,Bangalore,HTML CSS JS,1,520000
186,187,AI Engineer,TCS,Hyderabad,Python DL NLP,5,1500000
187,188,Business Analyst,Infosys,Pune,Excel BI SQL,3,720000
188,189,Python Developer,Wipro,Chennai,Python Django API,2,710000
189,190,SQL Developer,Amazon,Hyderabad,SQL ETL BI,3,940000
190,191,Data Analyst,Google,Bangalore,Excel SQL Python,2,640000
191,192,Data Scientist,Microsoft,Chennai,Python ML AI,4,1400000
192,193,Software Engineer,Accenture,Hyderabad,Java OOP SQL,2,720000
193,194,Machine Learning Engineer,Capgemini,Bangalore,Python ML NLP DL,4,1250000
194,195,Backend Developer,TCS,Pune,Python Django SQL,2,700000
195,196,Frontend Developer,Infosys,Hyderabad,React JS CSS HTML,2,780000
196,197,AI Engineer,Wipro,Chennai,Python AI NLP DL,5,1600000
197,198,Business Analyst,Amazon,Bangalore,Excel SQL BI,3,800000
198,199,Python Developer,Google,Pune,Python Flask API,2,760000
199,200,SQL Developer,Microsoft,Hyderabad,SQL ETL Power BI,3,960000

In [4]:
df.shape

(200, 7)

In [5]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
dtype: bool

In [6]:
df.isnull().sum()

job_id              0
job_title           0
company             0
location            0
skills_required     0
experience_years    0
salary              0
dtype: int64

In [7]:
df = df.drop(['company','location','experience_years','salary'],axis=1)
df

     job_id                  job_title              skills_required
0         1               Data Analyst             Python SQL Excel
1         2             Data Scientist  Python Machine Learning SQL
2         3          Software Engineer                 Java C++ SQL
3         4  Machine Learning Engineer      Python Deep Learning ML
4         5          Backend Developer              Python Java SQL
5         6         Frontend Developer          JavaScript HTML CSS
6         7                AI Engineer     Python NLP Deep Learning
7         8           Business Analyst           Excel SQL Power BI
8         9           Python Developer            Python Django SQL
9        10              SQL Developer             SQL Database ETL
10       11               Data Analyst            Excel SQL Tableau
11       12             Data Scientist             Python ML DL SQL
12       13          Software Engineer         Java Spring Boot SQL
13       14  Machine Learning Engineer                 Python ML AI
14       15          Backend Developer              Java Python SQL
15       16         Frontend Developer         JavaScript React CSS
16       17                AI Engineer     Python Deep Learning NLP
17       18           Business Analyst           Excel Power BI SQL
18       19           Python Developer             Python Flask SQL
19       20              SQL Developer     SQL ETL Data Warehousing
20       21               Data Analyst             Excel SQL Python
21       22             Data Scientist             Python ML AI SQL
22       23          Software Engineer                 Java C++ OOP
23       24  Machine Learning Engineer             Python ML DL NLP
24       25          Backend Developer            Python Django SQL
25       26         Frontend Developer          HTML CSS JavaScript
26       27                AI Engineer      Python Deep Learning AI
27       28           Business Analyst            Excel Tableau SQL
28       29           Python Developer             Python Flask API
29       30              SQL Developer             SQL ETL Power BI
30       31               Data Analyst             Excel SQL Python
31       32             Data Scientist                 Python ML DL
32       33          Software Engineer              Java Spring SQL
33       34  Machine Learning Engineer                Python ML NLP
34       35          Backend Developer            Python Django API
35       36         Frontend Developer                 React JS CSS
36       37                AI Engineer             Python AI DL NLP
37       38           Business Analyst                 Excel SQL BI
38       39           Python Developer             Python Flask SQL
39       40              SQL Developer                   SQL ETL DW
40       41               Data Analyst            Excel Tableau SQL
41       42             Data Scientist                 Python ML AI
42       43          Software Engineer                 Java OOP SQL
43       44  Machine Learning Engineer                 Python ML DL
44       45          Backend Developer              Java Python API
45       46         Frontend Developer                  HTML CSS JS
46       47                AI Engineer                Python DL NLP
47       48           Business Analyst                 Excel BI SQL
48       49           Python Developer            Python Django API
49       50              SQL Developer                   SQL ETL BI
50       51               Data Analyst             Excel SQL Python
51       52             Data Scientist                 Python ML AI
52       53          Software Engineer             Java Spring Boot
53       54  Machine Learning Engineer             Python ML NLP DL
54       55          Backend Developer            Python Django SQL
55       56         Frontend Developer            React JS CSS HTML
56       57                AI Engineer             Python AI NLP DL
57       58           Business Analyst                 Excel SQL BI
58       59           Python Developer             Python Flask API
59       60              SQL Developer             SQL ETL Power BI
60       61               Data Analyst             Excel SQL Python
61       62             Data Scientist              Python ML DL AI
62       63          Software Engineer                 Java OOP SQL
63       64  Machine Learning Engineer                Python ML NLP
64       65          Backend Developer               Python API SQL
65       66         Frontend Developer            HTML CSS JS React
66       67                AI Engineer             Python DL NLP AI
67       68           Business Analyst                 Excel BI SQL
68       69           Python Developer            Python Django SQL
69       70              SQL Developer                   SQL ETL DW
70       71               Data Analyst             Python SQL Excel
71       72             Data Scientist             Python ML AI SQL
72       73          Software Engineer         Java Spring Boot SQL
73       74  Machine Learning Engineer             Python ML NLP DL
74       75          Backend Developer            Python Django API
75       76         Frontend Developer            React JS CSS HTML
76       77                AI Engineer             Python AI NLP DL
77       78           Business Analyst                 Excel SQL BI
78       79           Python Developer             Python Flask API
79       80              SQL Developer             SQL ETL Power BI
80       81               Data Analyst             Excel SQL Python
81       82             Data Scientist              Python ML DL AI
82       83          Software Engineer                 Java OOP SQL
83       84  Machine Learning Engineer                Python ML NLP
84       85          Backend Developer               Python API SQL
85       86         Frontend Developer            HTML CSS JS React
86       87                AI Engineer             Python DL NLP AI
87       88           Business Analyst                 Excel BI SQL
88       89           Python Developer            Python Django SQL
89       90              SQL Developer                   SQL ETL DW
90       91               Data Analyst            Excel SQL Tableau
91       92             Data Scientist                 Python ML AI
92       93          Software Engineer             Java Spring Boot
93       94  Machine Learning Engineer                 Python ML DL
94       95          Backend Developer              Java Python API
95       96         Frontend Developer                  HTML CSS JS
96       97                AI Engineer                Python DL NLP
97       98           Business Analyst                 Excel BI SQL
98       99           Python Developer            Python Django API
99      100              SQL Developer                   SQL ETL BI
100     101               Data Analyst             Excel SQL Python
101     102             Data Scientist                 Python ML AI
102     103          Software Engineer                 Java OOP SQL
103     104  Machine Learning Engineer             Python ML NLP DL
104     105          Backend Developer            Python Django SQL
105     106         Frontend Developer            React JS CSS HTML
106     107                AI Engineer             Python AI NLP DL
107     108           Business Analyst                 Excel SQL BI
108     109           Python Developer             Python Flask API
109     110              SQL Developer             SQL ETL Power BI
110     111               Data Analyst             Excel SQL Python
111     112             Data Scientist              Python ML DL AI
112     113          Software Engineer                 Java OOP SQL
113     114  Machine Learning Engineer                Python ML NLP
114     115          Backend Developer               Python API SQL
115     116         Frontend Developer            HTML CSS JS React
116     117                AI Engineer             Python DL NLP AI
117     118           Business Analyst                 Excel BI SQL
118     119           Python Developer            Python Django SQL
119     120              SQL Developer                   SQL ETL DW
120     121               Data Analyst            Excel SQL Tableau
121     122             Data Scientist                 Python ML AI
122     123          Software Engineer             Java Spring Boot
123     124  Machine Learning Engineer                 Python ML DL
124     125          Backend Developer              Java Python API
125     126         Frontend Developer                  HTML CSS JS
126     127                AI Engineer                Python DL NLP
127     128           Business Analyst                 Excel BI SQL
128     129           Python Developer            Python Django API
129     130              SQL Developer                   SQL ETL BI
130     131               Data Analyst             Excel SQL Python
131     132             Data Scientist                 Python ML AI
132     133          Software Engineer                 Java OOP SQL
133     134  Machine Learning Engineer             Python ML NLP DL
134     135          Backend Developer            Python Django SQL
135     136         Frontend Developer            React JS CSS HTML
136     137                AI Engineer             Python AI NLP DL
137     138           Business Analyst                 Excel SQL BI
138     139           Python Developer             Python Flask API
139     140              SQL Developer             SQL ETL Power BI
140     141               Data Analyst             Excel SQL Python
141     142             Data Scientist              Python ML DL AI
142     143          Software Engineer                 Java OOP SQL
143     144  Machine Learning Engineer                Python ML NLP
144     145          Backend Developer               Python API SQL
145     146         Frontend Developer            HTML CSS JS React
146     147                AI Engineer             Python DL NLP AI
147     148           Business Analyst                 Excel BI SQL
148     149           Python Developer            Python Django SQL
149     150              SQL Developer                   SQL ETL DW
150     151               Data Analyst            Excel SQL Tableau
151     152             Data Scientist                 Python ML AI
152     153          Software Engineer             Java Spring Boot
153     154  Machine Learning Engineer                 Python ML DL
154     155          Backend Developer              Java Python API
155     156         Frontend Developer                  HTML CSS JS
156     157                AI Engineer                Python DL NLP
157     158           Business Analyst                 Excel BI SQL
158     159           Python Developer            Python Django API
159     160              SQL Developer                   SQL ETL BI
160     161               Data Analyst             Excel SQL Python
161     162             Data Scientist                 Python ML AI
162     163          Software Engineer                 Java OOP SQL
163     164  Machine Learning Engineer             Python ML NLP DL
164     165          Backend Developer            Python Django SQL
165     166         Frontend Developer            React JS CSS HTML
166     167                AI Engineer             Python AI NLP DL
167     168           Business Analyst                 Excel SQL BI
168     169           Python Developer             Python Flask API
169     170              SQL Developer             SQL ETL Power BI
170     171               Data Analyst             Excel SQL Python
171     172             Data Scientist              Python ML DL AI
172     173          Software Engineer                 Java OOP SQL
173     174  Machine Learning Engineer                Python ML NLP
174     175          Backend Developer               Python API SQL
175     176         Frontend Developer            HTML CSS JS React
176     177                AI Engineer             Python DL NLP AI
177     178           Business Analyst                 Excel BI SQL
178     179           Python Developer            Python Django SQL
179     180              SQL Developer                   SQL ETL DW
180     181               Data Analyst            Excel SQL Tableau
181     182             Data Scientist                 Python ML AI
182     183          Software Engineer             Java Spring Boot
183     184  Machine Learning Engineer                 Python ML DL
184     185          Backend Developer              Java Python API
185     186         Frontend Developer                  HTML CSS JS
186     187                AI Engineer                Python DL NLP
187     188           Business Analyst                 Excel BI SQL
188     189           Python Developer            Python Django API
189     190              SQL Developer                   SQL ETL BI
190     191               Data Analyst             Excel SQL Python
191     192             Data Scientist                 Python ML AI
192     193          Software Engineer                 Java OOP SQL
193     194  Machine Learning Engineer             Python ML NLP DL
194     195          Backend Developer            Python Django SQL
195     196         Frontend Developer            React JS CSS HTML
196     197                AI Engineer             Python AI NLP DL
197     198           Business Analyst                 Excel SQL BI
198     199           Python Developer             Python Flask API
199     200              SQL Developer             SQL ETL Power BI

In [8]:
df["skills_required"].value_counts()

skills_required
Python Django SQL              12
Excel SQL Python               12
Python ML AI                   11
Java OOP SQL                   10
Excel BI SQL                   10
SQL ETL Power BI                7
Python Django API               7
Excel SQL BI                    7
Python Flask API                7
React JS CSS HTML               6
SQL ETL DW                      6
Python ML NLP DL                6
Python ML DL                    6
Python ML NLP                   6
Python AI NLP DL                6
HTML CSS JS React               5
Python API SQL                  5
Python ML DL AI                 5
Java Spring Boot                5
Excel SQL Tableau               5
Java Python API                 5
HTML CSS JS                     5
Python DL NLP                   5
SQL ETL BI                      5
Python DL NLP AI                5
Excel Tableau SQL               2
Python SQL Excel                2
Python ML AI SQL                2
Python Flask SQL                2
Java Spring Boot SQL            2
Python Machine Learning SQL     1
Java Python SQL                 1
Java C++ SQL                    1
Python Deep Learning ML         1
Python Java SQL                 1
JavaScript HTML CSS             1
Python NLP Deep Learning        1
Excel SQL Power BI              1
SQL Database ETL                1
Python ML DL SQL                1
JavaScript React CSS            1
HTML CSS JavaScript             1
Python Deep Learning NLP        1
Excel Power BI SQL              1
SQL ETL Data Warehousing        1
Python AI DL NLP                1
React JS CSS                    1
Java C++ OOP                    1
Java Spring SQL                 1
Python ML DL NLP                1
Python Deep Learning AI         1
Name: count, dtype: int64

In [10]:
# converting the text data to feature vectors
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(df["skills_required"])

In [11]:
vectorizer.get_feature_names_out()

array(['ai', 'api', 'bi', 'boot', 'css', 'data', 'database', 'deep',
       'django', 'dl', 'dw', 'etl', 'excel', 'flask', 'html', 'java',
       'javascript', 'js', 'learning', 'machine', 'ml', 'nlp', 'oop',
       'power', 'python', 'react', 'spring', 'sql', 'tableau',
       'warehousing'], dtype=object)

In [12]:
pd.DataFrame(vectorizer.fit_transform(df["skills_required"]).toarray(),columns=vectorizer.get_feature_names_out())

,ai,api,bi,boot,css,data,database,deep,django,dl,...,ml,nlp,oop,power,python,react,spring,sql,tableau,warehousing
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.449510,0.000000,0.000000,0.489824,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.206158,0.000000,0.000000,0.224648,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.496219,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.653123,0.000000,0.000000,...,0.363781,0.000000,0.000000,0.000000,0.216838,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.414431,0.000000,0.000000,0.451599,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.480071,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.646627,0.000000,0.000000,...,0.000000,0.386665,0.000000,0.000000,0.214681,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.489178,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.689698,0.000000,0.000000,0.000000,0.292747,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.820452,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.386558,0.000000,0.000000,0.421227,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.836525,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.253207,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.324226,0.806466,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.611332,...,0.593630,0.000000,0.000000,0.000000,0.353844,0.000000,0.000000,0.385578,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.620004,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.602715,0.249262,0.000000,0.000000
13,0.681912,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.628287,0.000000,0.000000,0.000000,0.374501,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.414431,0.000000,0.000000,0.451599,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.469274,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.527662,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.646627,0.000000,0.000000,...,0.000000,0.386665,0.000000,0.000000,0.214681,0.000000,0.000000,0.000000,0.000000,0.000000
17,0.000000,0.000000,0.489178,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.689698,0.000000,0.000000,0.000000,0.292747,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.337519,0.000000,0.000000,0.367790,0.000000,0.000000
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.641628,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.194214,0.000000,0.641628
20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.449510,0.000000,0.000000,0.489824,0.000000,0.000000
21,0.631363,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.581713,0.000000,0.000000,0.000000,0.346740,0.000000,0.000000,0.377837,0.000000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.789228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.545161,...,0.529375,0.568327,0.000000,0.000000,0.315543,0.000000,0.000000,0.000000,0.000000,0.000000
24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.820452,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.386558,0.000000,0.000000,0.421227,0.000000,0.000000
25,0.000000,0.000000,0.000000,0.000000,0.480071,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,0.390261,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.645564,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.214329,0.000000,0.000000,0.000000,0.000000,0.000000
27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.324226,0.806466,0.000000
28,0.000000,0.583444,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.294779,0.000000,0.000000,0.000000,0.000000,0.000000
29,0.000000,0.000000,0.462997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.652785,0.000000,0.000000,0.000000,0.277079,0.000000,0.000000
30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.449510,0.000000,0.000000,0.489824,0.000000,0.000000
31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.662565,...,0.643380,0.000000,0.000000,0.000000,0.383497,0.000000,0.000000,0.000000,0.000000,0.000000
32,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.768183,0.317694,0.000000,0.000000
33,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.631462,0.677926,0.000000,0.000000,0.376394,0.000000,0.000000,0.000000,0.000000,0.000000
34,0.000000,0.644800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.691449,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.325778,0.000000,0.000000,0.000000,0.000000,0.000000
35,0.000000,0.000000,0.000000,0.000000,0.545450,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.613316,0.000000,0.000000,0.000000,0.000000
36,0.560743,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.532053,...,0.000000,0.554662,0.000000,0.000000,0.307956,0.000000,0.000000,0.000000,0.000000,0.000000
37,0.000000,0.000000,0.675570,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.404293,0.000000,0.000000
38,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.337519,0.000000,0.000000,0.367790,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.297917,0.000000,0.000000
40,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.324226,0.806466,0.000000
41,0.681912,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.628287,0.000000,0.000000,0.000000,0.374501,0.000000,0.000000,0.000000,0.000000,0.000000
42,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.744690,0.000000,0.000000,0.000000,0.000000,0.331182,0.000000,0.000000
43,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.662565,...,0.643380,0.000000,0.000000,0.000000,0.383497,0.000000,0.000000,0.000000,0.000000,0.000000
44,0.000000,0.676800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.341945,0.000000,0.000000,0.000000,0.000000,0.000000
45,0.000000,0.000000,0.000000,0.000000,0.562614,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
46,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.642584,...,0.000000,0.669890,0.000000,0.000000,0.371932,0.000000,0.000000,0.000000,0.000000,0.000000
47,0.000000,0.000000,0.675570,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.404293,0.000000,0.000000
48,0.000000,0.644800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.691449,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.325778,0.000000,0.000000,0.000000,0.000000,0.000000
49,0.000000,0.000000,0.611183,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.365761,0.000000,0.000000
50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.449510,0.000000,0.000000,0.489824,0.000000,0.000000
51,0.681912,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.628287,0.000000,0.000000,0.000000,0.374501,0.000000,0.000000,0.000000,0.000000,0.000000
52,0.000000,0.000000,0.000000,0.640212,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.622359,0.000000,0.000000,0.000000
53,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.545161,...,0.529375,0.568327,0.000000,0.000000,0.315543,0.000000,0.000000,0.000000,0.000000,0.000000
54,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.820452,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.386558,0.000000,0.000000,0.421227,0.000000,0.000000
55,0.000000,0.000000,0.000000,0.000000,0.475461,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.534619,0.000000,0.000000,0.000000,0.000000
56,0.560743,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.532053,...,0.000000,0.554662,0.000000,0.000000,0.307956,0.000000,0.000000,0.000000,0.000000,0.000000
57,0.000000,0.000000,0.675570,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.404293,0.000000,0.000000
58,0.000000,0.583444,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.294779,0.000000,0.000000,0.000000,0.000000,0.000000
59,0.000000,0.000000,0.462997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.652785,0.000000,0.000000,0.000000,0.277079,0.000000,0.000000
60,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.449510,0.000000,0.000000,0.489824,0.000000,0.000000
61,0.572522,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.543230,...,0.527500,0.000000,0.000000,0.000000,0.314425,0.000000,0.000000,0.000000,0.000000,0.000000
62,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.744690,0.000000,0.000000,0.000000,0.000000,0.331182,0.000000,0.000000
63,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.631462,0.677926,0.000000,0.000000,0.376394,0.000000,0.000000,0.000000,0.000000,0.000000
64,0.000000,0.801059,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.404726,0.000000,0.000000,0.441024,0.000000,0.000000
65,0.000000,0.000000,0.000000,0.000000,0.475461,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.534619,0.000000,0.000000,0.000000,0.000000
66,0.560743,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.532053,...,0.000000,0.554662,0.000000,0.000000,0.307956,0.000000,0.000000,0.000000,0.000000,0.000000
67,0.000000,0.000000,0.675570,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.404293,0.000000,0.000000
68,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.820452,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.386558,0.000000,0.000000,0.421227,0.000000,0.000000
69,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.297917,0.000000,0.000000
70,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.449510,0.000000,0.000000,0.489824,0.000000,0.000000
71,0.631363,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.581713,0.000000,0.000000,0.000000,0.346740,0.000000,0.000000,0.377837,0.000000,0.000000
72,0.000000,0.000000,0.000000,0.620004,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.602715,0.249262,0.000000,0.000000
73,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.545161,...,0.529375,0.568327,0.000000,0.000000,0.315543,0.000000,0.000000,0.000000,0.000000,0.000000
74,0.000000,0.644800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.691449,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.325778,0.000000,0.000000,0.000000,0.000000,0.000000
75,0.000000,0.000000,0.000000,0.000000,0.475461,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.534619,0.000000,0.000000,0.000000,0.000000
76,0.560743,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.532053,...,0.000000,0.554662,0.000000,0.000000,0.307956,0.000000,0.000000,0.000000,0.000000,0.000000
77,0.000000,0.000000,0.675570,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.404293,0.000000,0.000000
78,0.000000,0.583444,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.294779,0.000000,0.000000,0.000000,0.000000,0.000000
79,0.000000,0.000000,0.462997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.652785,0.000000,0.000000,0.000000,0.277079,0.000000,0.000000
80,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.449510,0.000000,0.000000,0.489824,0.000000,0.000000
81,0.572522,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.543230,...,0.527500,0.000000,0.000000,0.000000,0.314425,0.000000,0.000000,0.000000,0.000000,0.000000
82,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.744690,0.000000,0.000000,0.000000,0.000000,0.331182,0.000000,0.000000
83,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.631462,0.677926,0.000000,0.000000,0.376394,0.000000,0.000000,0.000000,0.000000,0.000000
84,0.000000,0.801059,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.404726,0.000000,0.000000,0.441024,0.000000,0.000000
85,0.000000,0.000000,0.000000,0.000000,0.475461,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.534619,0.000000,0.000000,0.000000,0.000000
86,0.560743,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.532053,...,0.000000,0.554662,0.000000,0.000000,0.307956,0.000000,0.000000,0.000000,0.000000,0.000000
87,0.000000,0.000000,0.675570,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.404293,0.000000,0.000000
88,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.820452,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.386558,0.000000,0.000000,0.421227,0.000000,0.000000
89,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.297917,0.000000,0.000000
90,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.324226,0.806466,0.000000
91,0.681912,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.628287,0.000000,0.000000,0.000000,0.374501,0.000000,0.000000,0.000000,0.000000,0.000000
92,0.000000,0.000000,0.000000,0.640212,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.622359,0.000000,0.000000,0.000000
93,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.662565,...,0.643380,0.000000,0.000000,0.000000,0.383497,0.000000,0.000000,0.000000,0.000000,0.000000
94,0.000000,0.676800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.341945,0.000000,0.000000,0.000000,0.000000,0.000000
95,0.000000,0.000000,0.000000,0.000000,0.562614,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
96,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.642584,...,0.000000,0.669890,0.000000,0.000000,0.371932,0.000000,0.000000,0.000000,0.000000,0.000000
97,0.000000,0.000000,0.675570,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.404293,0.000000,0.000000
98,0.000000,0.644800,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.691449,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.325778,0.000000,0.000000,0.000000,0.000000,0.000000
99,0.000000,0.000000,0.611183,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.365761,0.000000,0.000000
100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.449510,0.000000,0.000000,0.489824,0.000000,0.000000
101,0.681912,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.628287,0.000000,0.000000,0.000000,0.374501,0.000000,0.000000,0.000000,0.000000,0.000000
102,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.744690,0.000000,0.000000,0.000000,0.000000,0.331182,0.000000,0.000000
103,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.545161,...,0.529375,0.568327,0.000000,0.000000,0.315543,0.000000,0.000000,0.000000,0.000000,0.000000
104,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.820452,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.386558,0.000000,0.000000,0.421227,0.000000,0.000000
105,0.000000,0.000000,0.000000,0.000000,0.475461,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.534619,0.000000,0.000000,0.000000,0.000000

In [13]:
# getting the similarity scores using cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.2027078  0.24305974 ... 0.65860833 0.13250584 0.13572004]
 [0.2027078  1.         0.11147435 ... 0.09082339 0.06077108 0.0622452 ]
 [0.24305974 0.11147435 1.         ... 0.20061776 0.         0.13749204]
 ...
 [0.65860833 0.09082339 0.20061776 ... 1.         0.         0.42480838]
 [0.13250584 0.06077108 0.         ... 0.         1.         0.        ]
 [0.13572004 0.0622452  0.13749204 ... 0.42480838 0.         1.        ]]

In [14]:
print(similarity.shape)

(200, 200)

In [15]:
df["job_title"].tolist()

['Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer']

In [18]:
skills = input("Enter your skills: ").split(",")
skills = [skill.strip() for skill in skills]

user_input = " ".join(skills)

user_vector = vectorizer.transform([user_input])

similarity_scores = cosine_similarity(user_vector, feature_vectors)

# flatten the array (2D → 1D)
similarity_scores = similarity_scores.flatten()

# get top 5 indices (highest similarity)
top_5_indices = similarity_scores.argsort()[-10:][::-1]

print("\nTop 5 Job Recommendations:\n")

for i in top_5_indices:
    print(f"Job: {df['job_title'].iloc[i]} |  Match Score: {(similarity_scores[i])}")

Enter your skills:  Python, SQL, HTML, CSS, ML, AI, Power BI

Top 5 Job Recommendations:

Job: Business Analyst |  Match Score: 0.5710123625133774
Job: Business Analyst |  Match Score: 0.5710123625133774
Job: Data Scientist |  Match Score: 0.5525538739873715
Job: Data Scientist |  Match Score: 0.5525538739873715
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618